### PR TITLE
Allow RGs to be same

### PR DESCRIPTION
**Pull request by paulzhang97**
- Support that some or all of the RGs can be the same.
- Create separate TF variable for setting the RG name prefix.

### Test input tf vars
[byovnet.4rgs.auto.tfvars.json](https://github.com/user-attachments/files/17922467/byovnet.4rgs.auto.tfvars.json)
[byovnet.all-same-rgs.auto.tfvars.json](https://github.com/user-attachments/files/17922468/byovnet.all-same-rgs.auto.tfvars.json)
[byovnet.some-same-rgs.auto.tfvars.json](https://github.com/user-attachments/files/17922469/byovnet.some-same-rgs.auto.tfvars.json)
[byovnet.some-same-rgs1.auto.tfvars.json](https://github.com/user-attachments/files/17922470/byovnet.some-same-rgs1.auto.tfvars.json)

### CODE REVIEW

**Comment by david-yu** [comment]
@paulzhang97 Could you describe how you tested whether re-using the rg that the network your bring creates a cluster? Is it possible to show your tfvars file and the vnets and rgs that exist afterwards via az cli?

**Comment by paulzhang97** [comment]
> @paulzhang97 Could you describe how you tested whether re-using the rg that the network your bring creates a cluster? Is it possible to show your tfvars file and the vnets and rgs that exist afterwards via az cli?

Added those to the PR description.

**Review by ncole — APPROVED** [review]

**Comment by david-yu** [comment]
Thank you. L

**Review by david-yu — APPROVED** [review]

**Comment by paulzhang97** [comment]
I can't merge it until I merge the certification tests changes.

**Pull request merged**
